name: generate DBC files

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run the nix app
      run: |
        git status 
        nix build .\#default

    - name: Get current date and time
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H_%M_%S')"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}-${{ steps.date.outputs.date }} 
        files: | 
          ./result/*.dbc

    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dbc-files
        path: |
          ./result/*.dbc
