name: generate DBC and C code

on:
  pull_request:
    branches:
      - "main"
      - "develop"
  push:
    branches:
      - "main"  

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # This action checks out your repository's code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Replace '3.x' with your Python version
          
      - name: install dependencies
        id: installdeps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        continue-on-error: true
      - name: Check on failures
        if: steps.installdeps.outcome != 'success'
        run: |
          pip install pipreqs
          pipreqs .
          pip install -r requirements.txt
          
      - name: Run Python script
        run: |
          git status 
          rm -rf ./dbc-output
          python json_to_dbc.py can_descriptor.json ./dbc-output/ksu_ev_dbc Orion RMS_PM
          python json_to_dbc.py can_descriptor.json ./dbc-output/ksu_dbc Orion RMS_PM Megasquirt

      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H_%M_%S')"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}-${{ steps.date.outputs.date }} 
          files: | 
            # ./dbc-files/*.dbc
            ./dbc-output/*.dbc
            # *.json
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dbc-files
          path: |
            ./dbc-output/*.dbc
